# Compiler
CXX = g++

# Output executable path
OUT = ../builds/harmonogram

# Source files (all .cpp files in the current directory)
SRC = $(wildcard *.cpp)

# Compilation rule
$(OUT): $(SRC)
	$(CXX) -o $(OUT) $(SRC)

# Clean build files
# clean:
#	rm -f $(OUT)

